import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./colors.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <Header />
      
        <div className="page-wrapper max-w-5xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
